// ObservatorConstants.cs (logging constants removed)
namespace Observator.Generator;

public static class ObservatorConstants
{
    public const string ObservatorTraceAttributeFullName = "Observator.ObservatorTraceAttribute";
    public const string ObservatorTraceShortName = "ObservatorTrace";
    public const string TaskReturnType = "Task";
    public const string ValueTaskReturnType = "ValueTask";
    public const string AutoGeneratedComment = "// <auto-generated />";
    public const string InterceptsLocationAttributeName = "InterceptsLocationAttribute";
    public const string ActivitySetStatusError = "activity?.SetStatus(System.Diagnostics.ActivityStatusCode.Error, exception.Message)";
    public const string ActivitySetStatusOk = "activity?.SetStatus(activity.Status == System.Diagnostics.ActivityStatusCode.Unset ? System.Diagnostics.ActivityStatusCode.Ok : activity.Status, activity.StatusDescription)?.Dispose()";
}