name: Publish to NuGet

on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v5
      - name: Setup .NET
        uses: actions/setup-dotnet@v5
        with:
          dotnet-version: 9.0.x
      - name: Build solution
        run: dotnet build -c Release
      - name: Create version string
        id: version
        run: |
          if [ "${GITHUB_REF}" != "refs/heads/main" ]; then
            echo "VERSION=${GITHUB_RUN_NUMBER}-preview" >> $GITHUB_ENV
          else
            echo "VERSION=${GITHUB_RUN_NUMBER}" >> $GITHUB_ENV
          fi
      - name: Create NuGet package
        run: dotnet pack -c Release -o ./artifacts -p:Version=0.0.${VERSION} ./src/Observator
      - name: Publish package to nuget.org
        run: dotnet nuget push ./artifacts/*.nupkg -k ${{ secrets.GITHUB_TOKEN }} -s https://nuget.pkg.github.com/psimsa/index.json
      - name: Upload package
        uses: actions/upload-artifact@v5
        with:
          path: ./artifacts/*.nupkg