name: Publish to NuGet

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Fetch static secrets from Akeyless
        uses: akeyless-community/akeyless-github-action@v1.1.3
        id: fetch-secrets
        with:
          access-id: ${{ secrets.AKEYLESS_ACCESS_ID }}
          access-key: ${{ secrets.AKEYLESS_ACCESS_KEY }}
          access-type: access_key
          static-secrets: |
            - name: "/keys/nuget"
              output-name: "NUGET_API_KEY"
      - name: Create NuGet package
        run: dotnet pack -c Release -o ./artifacts -p:Version=${GITHUB_REF#refs/tags/v}
      - name: Publish package to nuget.org
        run: dotnet nuget push ./artifacts/*.nupkg -k ${{ steps.fetch-secrets.outputs.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json